# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4ed5a7443bdc913e8a882e9cee9e6f84181e537ab4620b29f257ccf0365954f8e7118980892ffb192beaa829d7164366a8cf61d9b1b563fca029049874234de

test:
  secret_key_base: e6b376718c74d2a01c4e125141c24765328df9cb22fc0eb74b5a91d30930d7d84a985f5c3c7528bae29c1b74f1ec9687d6872ce56220c3e1a08c0d27f8d7b546

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
